/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package git_lin;

public class App {
    /*
      path to repository (temp)
      JGit does not support paths with Cyrillic characters
     */
    static String repoPath = "/tests/test_simple/.git";

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());
        Main main = new Main();
        String currentDir = System.getProperty("user.dir");
        String newRepoPath = currentDir.substring(0, currentDir.lastIndexOf('\\')) + repoPath;
        main.openrepo(newRepoPath);
    }
}
