/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package git_lin;

public class App {
    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());
        Main main = new Main();
        main.openrepo("C:/Users/parsh/Desktop/gitlin/git_history_linearizer");
    }
}
