/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package git_lin;

public class App {
    /*
      path to repository (temp)
      JGit does not support paths with Cyrillic characters
     */
    static String repoPath = "C:/Users/parsh/Desktop/gitlin/git_history_linearizer";

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());
        Main main = new Main();
        main.openrepo(repoPath);
    }
}
